# Generated by Django 5.2.5 on 2025-08-16 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, null=True)),
                ('to_address', models.EmailField(max_length=100)),
                ('from_address', models.EmailField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('menuId', models.CharField(max_length=100, null=True)),
                ('type', models.IntegerField(choices=[(1, 'File'), (2, 'Folder')], default=1)),
                ('link', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.TextField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.CharField(max_length=100)),
                ('lang', models.TextField()),
                ('genre', models.TextField()),
                ('story', models.TextField()),
                ('link', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'File'), (2, 'Folder')], default=1)),
                ('duration', models.TextField(blank=True, null=True)),
                ('more', models.TextField()),
                ('parent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('starcast', models.TextField()),
                ('menu', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True, null=True)),
                ('parentId', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='0', max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user.posts')),
            ],
        ),
        migrations.CreateModel(
            name='Trand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trands', to='user.posts')),
            ],
        ),
    ]
