# Generated by Django 5.2.5 on 2025-08-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='trand',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.DeleteModel(
            name='Trand',
        ),
    ]
