# Generated by Django 5.2.5 on 2025-08-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_posts_trand_delete_trand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='trand',
            field=models.IntegerField(default=0),
        ),
    ]
