# Generated by Django 5.2.5 on 2025-08-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_created_comments_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='link',
            field=models.JSONField(default=list),
        ),
    ]
